---
title: "drone-based-model"
output: html_document
date: "2023-12-25"
---

## Load packages

```{r, warning=FALSE}
library(glmnet)
library(raster)
library(tidyverse)
library(glue)
library(ggtern)
library(jsonlite)
library(sf)
library(stars)
```


## Load the data

```{r}
counts_path <- "clean_data/training.rds"

pixel_counts <- readRDS(counts_path)  |>
  mutate(notgrass = dead + sand)

pixel_counts
```


## Set the seed and split data

```{r}
set.seed(8675309)

training_split <- pixel_counts |> 
  initial_split(strata = grass)

counts_train <- training_split |>
  training()

counts_test <- training_split |>
  testing()
```


Multinomial regression model with lasso regularization.

```{r}
non_predictors <- c("notgrass", "grass", "sand", "dead", "quadrat", "total", "quad_num","quad_quad")
predictors <- names(pixel_counts)[!names(pixel_counts) %in% non_predictors]
```


Formulate response and predictors

```{r}
y <- counts_train |>
  dplyr::select(c(grass, sand, dead)) |>
  as.matrix()

x <- counts_train |>
  dplyr::select(predictors) |>
  as.matrix()
```


Fit the model with cross validation

```{r}
fit <- cv.glmnet(x, y , family = "multinomial", type.multinomial = "grouped")
```

## Save fit

```{r}
multinomial_fit <- fit
saveRDS(multinomial_fit, 'clean_data/mutlinomial_fit.rds')
```


## Plot the object fit 

```{r}
plot(fit)
```

```{r}
options(scipen = 999)
coefficients <- coef(fit, s = "lambda.min")
coefficients
```

## Test response

```{r}
test_y <- counts_test |>
  dplyr::select(c(grass, sand, dead)) |>
  rowwise() |>
  mutate(total = sum(grass, sand, dead)) |>
  mutate(dead.obs = dead/total,
         grass.obs = grass/total,
         sand.obs = sand/total) |>
  dplyr::select(-c(total, grass, dead, sand)) |>
  ungroup()
  

test_x <- counts_test |>
  dplyr::select(predictors) |>
  as.matrix()

prediction <- predict(fit, newx = test_x, s = "lambda.min", type = 'response') |>
  as_tibble() |>
  rename(dead.pred = dead.1, grass.pred = grass.1, sand.pred = sand.1)
```

Extract test RMSE

```{r}
n  <- nrow(test_y)

error <- bind_cols(prediction, test_y) |>
  pivot_longer(everything(), names_to = c("type", ".value"), names_sep = "\\.") |>
  rowwise() |>
  mutate(squard_error = (pred -obs)^2) |>
  ungroup()

rmse <- sqrt(sum(error$squard_error)/n)

print('Total root mean squared error')
print(rmse)
```


Plot on ternary diagram

```{r}
error |> 
  ggplot(aes(obs, pred, color = type)) +
  geom_point() +
  geom_abline() +
  theme_minimal()
```


```{r}
data <- bind_cols(prediction, test_y) |>
  dplyr::select(dead.obs, grass.obs, sand.obs, dead.pred, grass.pred, sand.pred) |>
  mutate(id = 1:nrow(prediction)) |>
  pivot_longer(ends_with(c("obs","pred")), names_to = c(".value", "type"), names_sep = "\\.") 
data
```

```{r Ternary with points}
data |>
  ggtern(aes(dead, grass, sand, group = id)) +
  geom_point() +
  theme_rgbw()
```

```{r Ternary with arrows}
data |>
  ggtern(aes(dead, grass, sand, group = id)) +
  geom_path(arrow = arrow(length = unit( 0.05, "inches"))) +
  theme_rgbw()
```
