---
title: "map-statistics"
format: html
---

# Read in libraries

```{r}
library(conflicted)
library(terra)
library(tidyverse)
library(ggplot2)
library(viridis)

conflict_prefer("extract", "terra")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
```


# Read in coverage map, slope, mask, and digital elevation model

```{r}
dem <- terra::rast("clean_data/drone_sitched/dem.tif")

coverage <- terra::rast('clean_data/drone_sitched/pred_map.tif') |>
  terra::project(crs(dem))

mask <- terra::vect('clean_data/drone_sitched/Mask_Grass_Paper.shp') |>
  terra::project(crs(dem))

if(!file.exists('outputs/slope.tif')){
  slope <- terra::terrain(dem, v="slope", unit="degrees") |>
    terra::project(crs(dem))
  
  terra::writeRaster(slope, 'outputs/slope.tif')
} else {
  slope <- terra::rast('outputs/slope.tif') |>
    terra::project(crs(dem))
}
```

# Plot mask over orthos

```{r}
create_plot <- function(raster, title, mask = NULL, color_scale = viridis::viridis) {
  plot(raster, main = title, col = color_scale(100))
  
  if (!is.null(mask)) {
    lines(mask, col = "red", lwd = 2)
  }
}

create_plot(dem, "Digital Elevation Model with Mask", mask = mask)
create_plot(coverage, "Vegetation Coverage with Mask", mask = mask)
create_plot(slope, "Slope with Mask", mask = mask, color_scale = terrain.colors)
```

## Create data

```{r}
coverage[coverage == 4] <- NA 
coverage <- terra::project(coverage, crs(slope))

coverage_resampled <- terra::resample(coverage, slope, method="bilinear")

sand_df <- coverage_resampled |>
  terra::mask(mask, inverse=TRUE) |>
  terra::as.data.frame(xy=TRUE) |>
  as_tibble() |>
  rename(sand = 3) |>  
  filter(!is.na(sand))  

slope_df <- slope |>
  terra::mask(mask, inverse=TRUE) |>
  terra::as.data.frame(xy=TRUE) |>
  as_tibble() |>
  rename(slope = 3) |>  
  filter(!is.na(slope))  

data <- sand_df |> 
  inner_join(slope_df, by = c("x", "y"))
data
```
# Visual check

```{r}
sand_raster <- data |>
  select(-slope) |>
  terra::rast(
    crs = crs(coverage_resampled),  
    extent = ext(coverage_resampled),  
  )

slope_raster <- data |>
  select(-sand) |>
  terra::rast(
    crs = crs(slope),  
    extent = ext(slope),  
  )

create_plot(sand_raster, "Sand")
create_plot(slope_raster, "Slope")
```

