---
title: "map-creation"
output: html_document
date: "2023-12-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load libraries

```{r Load packages}
library(sf)
library(glcm)
library(terra)
library(glmnet)
source('src/orthomosaic-layer-generation.R')
```

## Read in drone orthomosaic

```{r}
multinomial_fit <- readRDS('clean_data/mutlinomial_fit.rds')
coefficients <-  coef(multinomial_fit, s = 'lambda.min')
cosefficients
```

## Read in proccessed orthomsaic 

```{r, warning=FALSE}
processed_ortho_path <- 'clean_data/processed_ortho.tif'
processed_ortho <-terra::rast(processed_ortho_path)

print(names(processed_ortho))
```

## Create composition map

Define prediction function

```{r}
predict_ortho <- function(model, x){
    x <- as.matrix(x)
    p <- predict(model, newx = x, type = "response", s = 'lamda.min')[,,1]
  
  if(is.matrix(p)){
    p <- as_tibble(p)
  } else {
    p <- tibble(dead = p["dead"], grass = p["grass"], sand = p["sand"])
  }
  return(p)
}
```

Predict across the entire orthomosaic

```{r}
composition <- processed_ortho |>
  predict(multinomial_fit, fun = predict_ortho, filename = "clean_data/orthomosaic_composition.tif", overwrite = TRUE)
compostion
```


